backend:
  name: git-gateway
  branch: main
  commit_messages:
    create: Create {{collection}} “{{slug}}”
    update: Update {{collection}} “{{slug}}”
    delete: Delete {{collection}} “{{slug}}”
    uploadMedia: Upload “{{path}}”
    deleteMedia: Delete “{{path}}”
    openAuthoring: '{{message}}'


logo_url: source/img/favicon.jpg

publish_mode: editorial_workflow

media_folder: "source/img/2025"
public_folder: "/img/2025"

site_url: https://wanglovema.netlify.app/
display_url: https://wanglovema.netlify.app/


locale: "zh_Hans"
common_col_conf: &common_col_conf
  create: true
  slug: "{{fields.filename}}"
  sortable_fields:
    - "commit_date"
    - "title"
    - "date"
    - "updated"
  # https://decapcms.org/docs/widgets/
  fields:
    - label: "文件名"
      name: "filename"
      widget: "string"
    - label: "标题"
      name: "title"
      widget: "string"
    - label: "发表日期"
      name: "date"
      widget: "datetime"
      format: "YYYY-MM-DD HH:mm:ss"
      date_format: "YYYY-MM-DD"
      time_format: "HH:mm:ss"
    - label: "更新日期"
      name: "updated"
      widget: "datetime"
      format: "YYYY-MM-DD HH:mm:ss"
      date_format: "YYYY-MM-DD"
      time_format: "HH:mm:ss"
      required: false
    - label: "封面"
      name: "cover"
      widget: "image"
    - label: "标签"
      name: "tags"
      widget: "select"
      multiple: true
      options:
        - "日常"
        - "陪伴"
        - "相识"
        - "纪念日"
        - "第一次"
        - "相恋"
        - "礼物"
        - "旅行"
        - "好友"
        - "责任"
        - "约定"
        - "爱好"
        - "爱意"
        - "节日"
        - "承诺"
        - "旅途"
        - "恋爱"
        - "亲情"
    - label: "正文"
      name: "body"
      widget: "markdown"
collections:
  - name: "2024"
    label: "2024"
    folder: "source/_posts/2024"
    preview_path: "2024/{{filename}}/"
    <<: *common_col_conf
  - name: "2025.4"
    label: "2025.4"
    folder: "source/_posts/2025/2025.4"
    preview_path: "2025/2025.4/{{filename}}/"
    <<: *common_col_conf
  - name: "2025.5"
    label: "2025.5"
    folder: "source/_posts/2025/2025.5"
    preview_path: "2025/2025.5/{{filename}}/"
    <<: *common_col_conf
